// Browser-level acceptance journeys for the local access prototype.
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
const {chromium}=require('playwright');
const root=path.join(__dirname,'public'),out=process.env.ECHO_PORTAL_QA_OUTPUT||process.env.ECHO_QA_OUTPUT||'/tmp/echo-portal-qa';fs.mkdirSync(out,{recursive:true});
const mime={'.html':'text/html','.css':'text/css','.js':'text/javascript','.ttf':'font/ttf','.svg':'image/svg+xml','.webp':'image/webp'};
const server=http.createServer((req,res)=>{let requested=decodeURIComponent(new URL(req.url,'http://localhost').pathname);if(requested.endsWith('/'))requested+='index.html';const file=path.join(root,requested);if(!file.startsWith(root)||!fs.existsSync(file)||fs.statSync(file).isDirectory()){res.writeHead(404);res.end();return;}res.setHeader('Content-Type',mime[path.extname(file)]||'application/octet-stream');res.end(fs.readFileSync(file));});
(async()=>{
  await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port,portal=base+'/esports/acesso.html';
  let options={headless:true};if(process.env.ECHO_CHROMIUM_EXECUTABLE){options={...options,executablePath:process.env.ECHO_CHROMIUM_EXECUTABLE,args:['--disable-gpu','--disable-dev-shm-usage']};}else if(process.env.ECHO_CHROMIUM_MODULE){const {default:c}=await import(process.env.ECHO_CHROMIUM_MODULE);options={...options,executablePath:await c.executablePath(),args:c.args};}
  const browser=await chromium.launch(options);
  const report={browser:await browser.version(),checkedAt:new Date().toISOString(),viewports:[],journeys:[]};
  try{
    for(const [name,width,height] of [['desktop',1440,1000],['tablet',820,1180],['tablet-landscape',1180,820],['mobile',390,844],['small-mobile',320,740]]){
      const ctx=await browser.newContext({viewport:{width,height},hasTouch:width<1440,isMobile:width<621,reducedMotion:'reduce'}),page=await ctx.newPage(),errors=[],failed=[];
      page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.status()>=400)failed.push(r.url());});
      const go=async(area,extra='')=>{await page.goto(portal+'?area='+area+extra,{waitUntil:'networkidle'});};
      const act=async(name)=>page.locator('[data-action="'+name+'"]').first().click();
      const submit=async(type)=>page.locator('form[data-form="'+type+'"] button[type="submit"]').click();
      const check=async(label,screenshot=false)=>{await page.evaluate(()=>document.fonts.ready);const dims=await page.evaluate(()=>({scroll:document.documentElement.scrollWidth,viewport:innerWidth}));assert.ok(dims.scroll<=dims.viewport+1,`${name} ${label}: overflow ${JSON.stringify(dims)}`);if(screenshot&&['desktop','tablet','mobile'].includes(name)){await page.evaluate(()=>window.scrollTo({top:0,behavior:'instant'}));await page.screenshot({path:path.join(out,name+'-'+label+'.png'),fullPage:!(await page.locator('#portal-dialog').isVisible())});}};
      await go('central');await check('dashboard',true);
      await go('perfil');await page.fill('[name="nick"]','Raven Prime');await page.check('[name="crest"][value="vortex"]');await submit('profile');await page.reload({waitUntil:'networkidle'});assert.equal(await page.inputValue('[name="nick"]'),'Raven Prime');await check('profile',true);
      await go('inscricao','&evento=open');assert.match(await page.locator('.readiness-list').innerText(),/Crie sua equipe/);await page.locator('#portal-content a[data-route="equipe"]').click();await check('create-team',true);
      await page.fill('[name="name"]','Crimson Wolves');await page.fill('[name="tag"]','CW');await page.check('[name="crest"][value="nova"]');await submit('team');await page.waitForURL('**area=equipe&retomar=open');assert.equal(await page.locator('.roster-slot.captain h3').innerText(),'Raven Prime');
      await page.fill('[name="nick"]','raven prime');await submit('invite');assert.match(await page.locator('.form-error').innerText(),/já está no elenco/);
      await page.fill('[name="nick"]','Shadow');await submit('invite');assert.equal(await page.locator('.member-status.pending').count(),1);
      await go('inscricao','&evento=open');assert.match(await page.locator('.readiness-list').innerText(),/aguardando resposta/);assert.equal(await page.locator('[data-action="wizard-next"]').count(),0);
      await go('equipe');await act('accept-member');await act('fill-roster');assert.equal(await page.locator('.member-status.pending').count(),0);await page.locator('.team-invitation-help summary').click();assert.match(await page.locator('.invitation-readiness').innerText(),/3 de 3/);await check('team',true);
      await go('inscricao','&evento=open');await check('entry-team',true);await act('wizard-next');await submit('wizard-rules');assert.equal(await page.locator('.wizard-steps .current').innerText(),'2\nRegulamento');await page.check('[name="accepted"]');await submit('wizard-rules');await page.fill('[name="note"]','Disponíveis para o horário de exemplo.');await check('entry-review',true);await submit('register');await page.waitForURL(u=>u.searchParams.has('registro'));assert.match(await page.locator('.portal-heading .portal-status').innerText(),/Em análise/);
      const registrationURL=page.url();await check('registration',true);await page.reload({waitUntil:'networkidle'});assert.match(await page.locator('.roster-summary').innerText(),/Crimson Wolves/);
      await go('inscricao','&evento=open');assert.match(await page.locator('.portal-empty').innerText(),/já está no circuito/);
      await go('organizar');await check('organizer',true);await act('review-registration');await check('review-dialog',true);await page.selectOption('[name="decision"]','recusada');await submit('review');assert.ok(await page.locator('#portal-dialog').isVisible());await page.selectOption('[name="decision"]','confirmada');await page.fill('#portal-dialog [name="note"]','Elenco conferido na demonstração.');await submit('review');assert.equal(await page.locator('#portal-dialog').isVisible(),false);assert.equal(await page.locator('td .portal-status').innerText(),'Confirmada');
      await page.goto(registrationURL,{waitUntil:'networkidle'});await act('checkin');assert.match(await page.locator('.success-banner').innerText(),/pronta para a arena/);await check('checkin',true);
      // Changes to the current team must never mutate the submitted roster snapshot.
      await go('perfil');await page.fill('[name="nick"]','Shadow');await submit('profile');assert.match(await page.locator('.form-error').innerText(),/outro jogador/);await page.fill('[name="nick"]','Raven Reloaded');await submit('profile');
      await page.goto(registrationURL,{waitUntil:'networkidle'});assert.match(await page.locator('.roster-summary').innerText(),/Raven Prime/);assert.doesNotMatch(await page.locator('.roster-summary').innerText(),/Raven Reloaded/);
      await act('cancel-registration');await page.keyboard.press('Escape');assert.equal(await page.locator('#portal-dialog').isVisible(),false);assert.equal(await page.locator('.portal-heading .portal-status').innerText(),'Check-in realizado');await act('cancel-registration');await act('confirm-cancel-registration');assert.equal(await page.locator('.portal-heading .portal-status').innerText(),'Cancelada');
      await go('inscricao','&evento=syndicate');assert.match(await page.locator('.readiness-list').innerText(),/sindicato/);await page.locator('#portal-content a[data-route="equipe"]').first().click();await page.locator('.team-banner a[data-route="equipe"]').click();await page.fill('[name="syndicate"]','Sindicato Eclipse');await submit('team');await page.locator('.resume-banner a').click();await act('wizard-next');await page.check('[name="accepted"]');await submit('wizard-rules');await submit('register');const copaURL=page.url();await go('organizar');await act('review-registration');await page.selectOption('[name="decision"]','recusada');await page.fill('#portal-dialog [name="note"]','Vínculo do sindicato precisa de revisão.');await submit('review');await page.goto(copaURL,{waitUntil:'networkidle'});assert.match(await page.locator('.registration-details-grid').innerText(),/Vínculo do sindicato/);assert.equal(await page.locator('.portal-heading .portal-status').innerText(),'Recusada');
      await go('novo-evento');await page.fill('[name="name"]','Echo Legends Invitational');await page.selectOption('[name="format"]','Grupos + finais');await page.selectOption('[name="capacity"]','32');await page.fill('[name="description"]','Uma noite para escrever o próximo capítulo do circuito.');await page.fill('[name="rules"]','3 titulares e 1 reserva opcional.\nConfrontos em MD3.\nRespeito entre todas as equipes.');await check('event-studio',true);await submit('draft');assert.match(await page.locator('.draft-card').innerText(),/Echo Legends/);await act('preview-draft');assert.match(await page.locator('.draft-rules-preview').innerText(),/Confrontos em MD3/);await check('draft-preview',true);await page.keyboard.press('Escape');await page.locator('.draft-card a[data-route="novo-evento"]').click();
      // User-entered strings must render as text in both live previews and saved views.
      const injection='<img src=x onerror=alert(1)>';await page.fill('[name="name"]',injection);assert.equal(await page.locator('#preview-draft-name img').count(),0);assert.equal(await page.locator('#preview-draft-name').innerText(),injection);await submit('draft');assert.equal(await page.locator('.draft-card h3').innerText(),injection);assert.equal(await page.locator('.draft-card img').count(),0);await act('preview-draft');assert.equal(await page.locator('#portal-dialog .portal-event-poster h2').innerText(),injection);await act('close-dialog');await act('delete-draft');await act('confirm-delete-draft');assert.equal(await page.locator('.draft-card').count(),0);
      await page.goto(base+'/esports/',{waitUntil:'networkidle'});await page.locator('[data-follow="masters"]').click();await go('acompanhando');assert.equal(await page.locator('.portal-event-card').count(),1);await check('following',true);await act('unfollow');assert.equal(await page.locator('.portal-event-card').count(),0);await page.goto(base+'/esports/',{waitUntil:'networkidle'});assert.equal(await page.locator('[data-follow="masters"]').getAttribute('aria-pressed'),'false');
      await go('central');await page.locator((width<761?'.portal-mobile-nav':'.portal-nav')+' a[data-route="inscricoes"]').click();assert.match(page.url(),/area=inscricoes/);await check('registration-list',true);await act('filter-registrations');await page.goBack();assert.match(await page.locator('h1').innerText(),/conquista/i);
      assert.deepEqual(errors,[],name+' JS errors');assert.deepEqual(failed,[],name+' failed assets');report.viewports.push({name,width,height,status:'passed',horizontalOverflow:false,javascriptErrors:errors,failedAssets:failed});fs.writeFileSync(path.join(out,'validation.json'),JSON.stringify(report,null,2));console.log(name+': access journeys passed');await ctx.close();
    }
    // Storage denied: the in-session repository and a clear notice remain usable.
    const context=await browser.newContext();await context.addInitScript(()=>{Object.defineProperty(window,'localStorage',{get(){throw new DOMException('Storage disabled','SecurityError');}});});const p=await context.newPage();await p.goto(portal,{waitUntil:'networkidle'});assert.ok(await p.locator('#storage-banner').isVisible());await p.goto(portal+'?area=equipe',{waitUntil:'networkidle'});await p.fill('[name="name"]','Session Team');await p.fill('[name="tag"]','ST');await p.locator('form button[type="submit"]').click();assert.match(await p.locator('.team-banner').innerText(),/Session Team/i);assert.ok(await p.locator('#storage-banner').isVisible());await context.close();
    report.journeys=['Player identity and reload persistence','Team creation, duplicate player validation, pending invites and simulated acceptance','Registration readiness, rules acknowledgement and review','Duplicate registration prevention','Organizer approval and rejection with required reason','Check-in, cancellation confirmation and Escape','Submitted roster remains unchanged after profile edits','Syndicate eligibility requirement','Draft creation, editing, preview and deletion','User content escapes in all draft previews','Favorites shared with landing page','Mobile navigation and browser history','Desktop/tablet/mobile layout, zero page overflow','Storage denied: session-only mode with visible notice'];
    fs.writeFileSync(path.join(out,'validation.json'),JSON.stringify(report,null,2));console.log('Portal acceptance complete.');
  }finally{await browser.close();server.close();}
})().catch(e=>{const summary=String(e?.message||e).split(/\r?\n/,1)[0].replace(/%/g,'%25').replace(/\r/g,'%0D').replace(/\n/g,'%0A');console.error('::error title=Portal browser QA::'+summary);console.error(e);server.close();process.exitCode=1;});
